spring.application.name=grocery-backend
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis Plus config (optional logging)
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# Server config
server.port=${PORT:8080}

# Stripe Config (Test Mode)
# Replace with your real test secret key from stripe dashboard
stripe.secret.key=sk_test_51T7dTdAOBZ0b6qbnSLrkIwYmeu0UlolySZNYRd6qYC1t8leYxjQOfkaiOyrduIrQJYjUm0bgsKwuP0O2l8CVEphK00hDVlt0vL

