package com.grocery.grocerybackend.service;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.grocery.grocerybackend.dto.PurchaseOrderDTO;
import com.grocery.grocerybackend.dto.RestockCalculationResponse;
import com.grocery.grocerybackend.entity.*;
import com.grocery.grocerybackend.mapper.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class PurchaseOrderService {

    private final PurchaseOrderMapper purchaseOrderMapper;
    private final PurchaseOrderItemMapper purchaseOrderItemMapper;
    private final InventoryMetricsMapper inventoryMetricsMapper;
    private final ProductMapper productMapper;
    private final RestockOptimizer restockOptimizer;
    private final InventoryService inventoryService;
    private final StockMovementService stockMovementService;
    private final NotificationService notificationService;

    public PurchaseOrderService(PurchaseOrderMapper purchaseOrderMapper,
                                PurchaseOrderItemMapper purchaseOrderItemMapper,
                                InventoryMetricsMapper inventoryMetricsMapper,
                                ProductMapper productMapper,
                                RestockOptimizer restockOptimizer,
                                InventoryService inventoryService,
                                StockMovementService stockMovementService,
                                NotificationService notificationService) {
        this.purchaseOrderMapper = purchaseOrderMapper;
        this.purchaseOrderItemMapper = purchaseOrderItemMapper;
        this.inventoryMetricsMapper = inventoryMetricsMapper;
        this.productMapper = productMapper;
        this.restockOptimizer = restockOptimizer;
        this.inventoryService = inventoryService;
        this.stockMovementService = stockMovementService;
        this.notificationService = notificationService;
    }

    /**
     * Auto-generate purchase orders based on restock algorithm.
     * Groups all items needing restock into one PO.
     */
    @Transactional
    public PurchaseOrderDTO autoGeneratePO() {
        List<InventoryMetrics> allMetrics = inventoryMetricsMapper.selectList(null);
        Map<String, Product> skuMap = productMapper.selectList(null).stream()
                .filter(p -> p.getSku() != null)
                .collect(Collectors.toMap(Product::getSku, p -> p, (a, b) -> a));

        List<PurchaseOrderItem> itemsToOrder = new ArrayList<>();
        BigDecimal totalCost = BigDecimal.ZERO;

        for (InventoryMetrics metrics : allMetrics) {
            RestockCalculationResponse calc = restockOptimizer.calculateRestock(metrics);
            if (calc.getOrderQuantity() > 0) {
                Product product = skuMap.get(metrics.getSkuId());
                if (product == null) continue;

                PurchaseOrderItem item = new PurchaseOrderItem();
                item.setProductId(product.getId());
                item.setSku(product.getSku());
                item.setProductName(product.getName());
                item.setQuantityOrdered(calc.getOrderQuantity());
                item.setQuantityReceived(0);

                BigDecimal unitCost = product.getCostPrice() != null
                        ? product.getCostPrice()
                        : product.getPrice().multiply(new BigDecimal("0.7")); // estimate 70% of selling price
                item.setUnitCost(unitCost);
                item.setLineTotal(unitCost.multiply(BigDecimal.valueOf(calc.getOrderQuantity()))
                        .setScale(2, RoundingMode.HALF_UP));

                totalCost = totalCost.add(item.getLineTotal());
                itemsToOrder.add(item);
            }
        }

        if (itemsToOrder.isEmpty()) {
            return null; // nothing to restock
        }

        // Create PO
        PurchaseOrder po = new PurchaseOrder();
        po.setPoNumber(generatePoNumber());
        po.setSupplierName("Auto-Generated");
        po.setStatus("PENDING_APPROVAL");
        po.setTotalCost(totalCost);
        po.setTaxAmount(BigDecimal.ZERO);
        po.setNotes("Auto-generated by restock algorithm on " + LocalDate.now());
        po.setCreatedAt(new Timestamp(System.currentTimeMillis()));
        po.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
        purchaseOrderMapper.insert(po);

        // Insert items
        for (PurchaseOrderItem item : itemsToOrder) {
            item.setPurchaseOrderId(po.getId());
            purchaseOrderItemMapper.insert(item);
        }

        // Send notification to admin
        notificationService.createRestockNotification(po, itemsToOrder);

        return toDTO(po, itemsToOrder);
    }

    /**
     * Approve a purchase order.
     */
    @Transactional
    public PurchaseOrderDTO approvePO(Long poId) {
        PurchaseOrder po = purchaseOrderMapper.selectById(poId);
        if (po == null) throw new IllegalArgumentException("PO not found: " + poId);
        if (!"PENDING_APPROVAL".equals(po.getStatus())) {
            throw new IllegalStateException("Only PENDING_APPROVAL POs can be approved");
        }

        po.setStatus("APPROVED");
        po.setApprovedAt(new Timestamp(System.currentTimeMillis()));
        po.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
        purchaseOrderMapper.updateById(po);

        List<PurchaseOrderItem> items = purchaseOrderItemMapper.selectList(
                new QueryWrapper<PurchaseOrderItem>().eq("purchase_order_id", poId));
        return toDTO(po, items);
    }

    /**
     * Real-time trigger: Automatically generates a PO if a specific product drops below safety stock.
     */
    @Transactional
    public void triggerRealTimeRestock(Long productId) {
        Product product = productMapper.selectById(productId);
        if (product == null) return;

        InventoryMetrics metrics = inventoryMetricsMapper.selectOne(new QueryWrapper<InventoryMetrics>().eq("sku_id", product.getSku()));
        if (metrics == null) return;

        // Ensure current stock is evaluated
        metrics.setCurrentStock(product.getStockQuantity());

        // Run ML predictive algo dynamically for this item
        RestockCalculationResponse calc = restockOptimizer.calculateRestock(metrics);

        // If the algorithm determines we need more stock (netRequirement > 0 -> orderQuantity > 0)
        if (calc.getOrderQuantity() > 0) {
            
            // Check if there is already a PENDING_APPROVAL PO for this product
            List<PurchaseOrder> pendingPOs = purchaseOrderMapper.selectList(
                    new QueryWrapper<PurchaseOrder>().eq("status", "PENDING_APPROVAL"));
            if (!pendingPOs.isEmpty()) {
                List<Long> pendingPoIds = pendingPOs.stream().map(PurchaseOrder::getId).collect(Collectors.toList());
                Long count = purchaseOrderItemMapper.selectCount(new QueryWrapper<PurchaseOrderItem>()
                        .eq("product_id", productId)
                        .in("purchase_order_id", pendingPoIds));
                if (count > 0) return; // Already ordered, wait for arrival
            }

            // Create a rapid-action PO for this specific item
            PurchaseOrder po = new PurchaseOrder();
            po.setPoNumber(generatePoNumber());
            po.setSupplierName("Smart-Restock Trigger");
            po.setStatus("PENDING_APPROVAL");
            
            BigDecimal unitCost = product.getCostPrice() != null ? product.getCostPrice() 
                 : product.getPrice().multiply(new BigDecimal("0.7"));
            po.setTotalCost(unitCost.multiply(BigDecimal.valueOf(calc.getOrderQuantity())));
            po.setTaxAmount(BigDecimal.ZERO);
            po.setNotes("Auto-generated triggered by real-time safety stock drop for " + product.getName());
            po.setCreatedAt(new Timestamp(System.currentTimeMillis()));
            po.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
            purchaseOrderMapper.insert(po);

            PurchaseOrderItem item = new PurchaseOrderItem();
            item.setPurchaseOrderId(po.getId());
            item.setProductId(product.getId());
            item.setSku(product.getSku());
            item.setProductName(product.getName());
            item.setQuantityOrdered(calc.getOrderQuantity());
            item.setQuantityReceived(0);
            item.setUnitCost(unitCost);
            item.setLineTotal(po.getTotalCost().setScale(2, RoundingMode.HALF_UP));
            purchaseOrderItemMapper.insert(item);

            // Send notification to admin
            notificationService.createRestockNotification(po, List.of(item));
        }
    }

    /**
     * Receive a purchase order — creates batches, increments stock, logs movements.
     */
    @Transactional
    public PurchaseOrderDTO receivePO(Long poId) {
        PurchaseOrder po = purchaseOrderMapper.selectById(poId);
        if (po == null) throw new IllegalArgumentException("PO not found: " + poId);
        if (!"APPROVED".equals(po.getStatus())) {
            throw new IllegalStateException("Only APPROVED POs can be received");
        }

        List<PurchaseOrderItem> items = purchaseOrderItemMapper.selectList(
                new QueryWrapper<PurchaseOrderItem>().eq("purchase_order_id", poId));

        for (PurchaseOrderItem item : items) {
            int qty = item.getQuantityOrdered();
            item.setQuantityReceived(qty);
            purchaseOrderItemMapper.updateById(item);
        }

        po.setStatus("RECEIVED");
        po.setReceivedAt(new Timestamp(System.currentTimeMillis()));
        po.setUpdatedAt(new Timestamp(System.currentTimeMillis()));
        purchaseOrderMapper.updateById(po);

        return toDTO(po, items);
    }

    /**
     * List purchase orders, optionally filtered by status.
     */
    public List<PurchaseOrderDTO> listPOs(String status) {
        QueryWrapper<PurchaseOrder> qw = new QueryWrapper<>();
        if (status != null && !status.isBlank()) {
            qw.eq("status", status);
        }
        qw.orderByDesc("created_at");

        List<PurchaseOrder> pos = purchaseOrderMapper.selectList(qw);
        return pos.stream().map(po -> {
            List<PurchaseOrderItem> items = purchaseOrderItemMapper.selectList(
                    new QueryWrapper<PurchaseOrderItem>().eq("purchase_order_id", po.getId()));
            return toDTO(po, items);
        }).collect(Collectors.toList());
    }

    /**
     * Get single PO detail.
     */
    public PurchaseOrderDTO getPO(Long id) {
        PurchaseOrder po = purchaseOrderMapper.selectById(id);
        if (po == null) throw new IllegalArgumentException("PO not found: " + id);
        List<PurchaseOrderItem> items = purchaseOrderItemMapper.selectList(
                new QueryWrapper<PurchaseOrderItem>().eq("purchase_order_id", id));
        return toDTO(po, items);
    }

    /**
     * Export PO items as a CSV compatible with Bulk Upload.
     */
    public String exportPOtoCSV(Long id) {
        PurchaseOrder po = purchaseOrderMapper.selectById(id);
        if (po == null) throw new IllegalArgumentException("PO not found: " + id);
        
        List<PurchaseOrderItem> items = purchaseOrderItemMapper.selectList(
                new QueryWrapper<PurchaseOrderItem>().eq("purchase_order_id", id));
        
        Map<Long, Product> productMap = productMapper.selectList(null).stream()
                .collect(Collectors.toMap(Product::getId, p -> p, (a, b) -> a));

        StringBuilder csv = new StringBuilder();
        csv.append("sku,name,category,cost_price,stock_quantity,expiry_date,batch_no\n");

        String numericPo = po.getPoNumber().replaceAll("[^0-9]", "");
        String defaultBatchNo = "B" + (numericPo.isEmpty() ? po.getId() : numericPo);

        for (PurchaseOrderItem item : items) {
            Product p = productMap.get(item.getProductId());
            String category = (p != null) ? p.getCategory() : "General";
            
            csv.append(item.getSku()).append(",")
               .append("\"").append(item.getProductName()).append("\",")
               .append(category).append(",")
               .append(item.getUnitCost()).append(",")
               .append(item.getQuantityOrdered()).append(",")
               .append("").append(",") // expiry_date blank
               .append(defaultBatchNo).append("\n"); // batch_no linked to PO
        }

        return csv.toString();
    }

    // --- helpers ---

    private String generatePoNumber() {
        return "PO-" + System.currentTimeMillis() % 1_000_000;
    }

    private PurchaseOrderDTO toDTO(PurchaseOrder po, List<PurchaseOrderItem> items) {
        PurchaseOrderDTO dto = new PurchaseOrderDTO();
        dto.setId(po.getId());
        dto.setPoNumber(po.getPoNumber());
        dto.setSupplierName(po.getSupplierName());
        dto.setStatus(po.getStatus());
        dto.setTotalCost(po.getTotalCost());
        dto.setTaxAmount(po.getTaxAmount());
        dto.setNotes(po.getNotes());
        dto.setCreatedAt(po.getCreatedAt() != null ? po.getCreatedAt().toString() : null);
        dto.setApprovedAt(po.getApprovedAt() != null ? po.getApprovedAt().toString() : null);
        dto.setReceivedAt(po.getReceivedAt() != null ? po.getReceivedAt().toString() : null);

        dto.setItems(items.stream().map(item -> {
            PurchaseOrderDTO.ItemDTO idto = new PurchaseOrderDTO.ItemDTO();
            idto.setId(item.getId());
            idto.setProductId(item.getProductId());
            idto.setSku(item.getSku());
            idto.setProductName(item.getProductName());
            idto.setQuantityOrdered(item.getQuantityOrdered());
            idto.setQuantityReceived(item.getQuantityReceived());
            idto.setUnitCost(item.getUnitCost());
            idto.setLineTotal(item.getLineTotal());
            return idto;
        }).collect(Collectors.toList()));

        return dto;
    }
}
